image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.5.0
variables:
    MAVEN_OPTS: -Dmaven.repo.local=/cache
    BUILD_CI_NAME: $CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
cache:
    key: one-key-for-all
    paths:
    - target/
stages:
- build
- dev-release
build:
    stage: build
    script: "mvn -U clean compile"
    only:
    - tags
    - master
    - development
    - dev-0.8.5
    - /^release-.*$/

dev-release:
    stage: dev-release
    only:
    - tags
    - development
    - dev-0.8.5
    - /^release-.*$/
    when: manual
    script:
    - "mvn compile jib:build -Dregistry_url=$REGISTRY_URL -Dregistry_username=$REGISTRY_USERNAME -Dregistry_password=$REGISTRY_PASSWORD -Dci_pipeline_id=$BUILD_CI_NAME"