spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    change-log: classpath:db/liquibase/master.xml

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
